name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: 5.0.x
  #   - name: Build
  #     run: |
  #       cd src/
  #       dotnet restore
  #       dotnet build --no-restore -c Release
  #       cd ../
  #       ls bin/Release/HoneyBee.Diff.Gui/net5.0
  #   - name: Expose as artifact
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: HoneyBee-Linux
  #       path: bin/Release/HoneyBee.Diff.Gui/net5.0
        
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: |
        cd src/
        dotnet restore
        dotnet build --no-restore -c Release
        cd ../
        dir bin/Release/HoneyBee.Diff.Gui/net5.0
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: HoneyBee-Windows
        path: bin/Release/HoneyBee.Diff.Gui/net5.0
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: |
        cd src/
        dotnet restore
        dotnet build --no-restore -c Release
        cd ../
        ls bin/Release/HoneyBee.Diff.Gui/net5.0
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: HoneyBee-Macos
        path: bin/Release/HoneyBee.Diff.Gui/net5.0
        
  push-itch:
    runs-on: ubuntu-latest
    needs: [build-windows,build-macos]
    steps:
    - name: Download an artifact - windows
      uses: actions/download-artifact@v2
      with:
        name: HoneyBee-Windows
        path: windows/
    - name: Download an artifact - macos
      uses: actions/download-artifact@v2
      with:
        name: HoneyBee-Macos
        path: macos/
    - name: Check files
      run: |
        ls -alh ./
        ls -alh windows/
        ls -alh macos/
        
    - name: itch-butler-windows
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: HoneyBee
        ITCH_USER: wanderer-x
        PACKAGE: windows/
    
    - name: itch-butler-osx
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: osx
        ITCH_GAME: HoneyBee
        ITCH_USER: wanderer-x
        PACKAGE: macos/
